use_frameworks!

platform :ios, '8.0'

target 'QVCloudEngine_Example' do
  pod 'QVCloudEngine', :path => '../'
  pod 'YYWebImage'
  pod 'YYImage/WebP'
  pod 'SVProgressHUD'

  target 'QVCloudEngine_Tests' do
    inherit! :search_paths

    
  end
end
